apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mypipeline
spec:
  params:
    - name: repository
      type: string
    - name: image-name
      type: string
    - name: manifest-dir
      type: string
  workspaces:
  - name: workspace
  tasks:
  - name: clone-git-repo
    workspaces:
    - name: output
      workspace: workspace
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.repository)
      - name: deleteExisting
        value: "true"
  - name: secret-detection
    runAfter:
    - clone-git-repo
    taskRef:
      name: gitleaks
    workspaces:
      - name: source
        workspace: workspace
    params:
    - name: repo_path
      value: contest-arena
    - name: output_format
      value: json
    - name: report_output_path
      value: report.json
    - name: args
      value: ["--verbose", "--no-git"]
  - name: build
    runAfter:
    - clone-git-repo
    taskRef:
      name: build
    workspaces:
      - name: source
        workspace: workspace
    params:
      - name : image-name
        value: $(params.image-name)
  - name: check
    runAfter:
    - build
    taskRef:
      name: deploy
    workspaces:
      - name: source
        workspace: workspace
    params:
      - name: manifest-dir
        value: $(params.manifest-dir)
